import type {
  Project,
  Task,
  CreativeBrief,
  Campaign,
  Asset,
  ResourceItem,
  EventRecord,
  ContentItem,
  InboxItem,
} from './types'

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    name: 'Larchmont Brand Refresh 2024',
    status: 'Active',
    priority: 'High',
    category: 'Brand',
    entity: 'Larchmont',
    startDate: '2024-11-01',
    deadline: '2025-02-28',
    progress: 65,
    budget: 12000,
    notes: 'Full brand refresh including logo, color system, and brand guidelines doc.',
    briefIds: ['brief-001'],
    taskIds: ['task-001', 'task-002', 'task-003'],
    assetIds: ['asset-001', 'asset-002'],
    campaignIds: [],
    resourceIds: ['res-001', 'res-002'],
  },
  {
    id: 'proj-002',
    name: 'ScaleGenie Launch Campaign',
    status: 'Active',
    priority: 'Critical',
    category: 'Paid Ads',
    entity: 'ScaleGenie',
    startDate: '2024-12-01',
    deadline: '2025-01-31',
    progress: 40,
    budget: 25000,
    notes: 'Multi-channel launch campaign targeting SMB owners.',
    briefIds: ['brief-002'],
    taskIds: ['task-004', 'task-005', 'task-006'],
    assetIds: ['asset-003', 'asset-004'],
    campaignIds: ['camp-001'],
    resourceIds: ['res-003'],
  },
  {
    id: 'proj-003',
    name: 'Water Damage Hero Video',
    status: 'In Review',
    priority: 'High',
    category: 'Video',
    entity: 'Larchmont',
    startDate: '2024-10-15',
    deadline: '2025-01-20',
    progress: 85,
    budget: 8500,
    notes: 'Cinematic brand video showing the restoration process from damage to complete.',
    briefIds: ['brief-003'],
    taskIds: ['task-007', 'task-008'],
    assetIds: ['asset-005', 'asset-006'],
    campaignIds: ['camp-002'],
    resourceIds: ['res-004', 'res-005'],
  },
  {
    id: 'proj-004',
    name: 'ScaleGenie Website Redesign',
    status: 'Planning',
    priority: 'Medium',
    category: 'Web',
    entity: 'ScaleGenie',
    startDate: '2025-01-15',
    deadline: '2025-04-30',
    progress: 10,
    budget: 18000,
    notes: 'Full redesign of scalegenie.com with new brand and conversion focus.',
    briefIds: [],
    taskIds: ['task-009', 'task-010'],
    assetIds: [],
    campaignIds: [],
    resourceIds: ['res-006'],
  },
  {
    id: 'proj-005',
    name: 'Annual Customer Appreciation Event',
    status: 'Active',
    priority: 'Medium',
    category: 'Events',
    entity: 'Larchmont',
    startDate: '2024-12-01',
    deadline: '2025-01-25',
    progress: 50,
    budget: 5000,
    notes: 'Customer appreciation BBQ + brand activation. Targeting 200+ attendees.',
    briefIds: [],
    taskIds: ['task-011'],
    assetIds: ['asset-007'],
    campaignIds: [],
    resourceIds: [],
  },
  {
    id: 'proj-006',
    name: 'Print Collateral Suite',
    status: 'Paused',
    priority: 'Low',
    category: 'Print',
    entity: 'Larchmont',
    startDate: '2024-09-01',
    deadline: '2025-03-15',
    progress: 25,
    budget: 3200,
    notes: 'Business cards, brochures, door hangers, and vehicle wraps.',
    briefIds: [],
    taskIds: ['task-012'],
    assetIds: ['asset-008'],
    campaignIds: [],
    resourceIds: [],
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    name: 'Finalize logo mark variations (horizontal, stacked, icon)',
    projectId: 'proj-001',
    status: 'In Progress',
    priority: 'P0',
    dueDate: '2025-01-15',
    estimatedTime: '4h',
    type: 'Design',
    dependencyIds: [],
    notes: 'Need 3 variations: full lockup, horizontal, favicon-ready icon.',
  },
  {
    id: 'task-002',
    name: 'Build out brand guidelines document',
    projectId: 'proj-001',
    status: 'Not Started',
    priority: 'P1',
    dueDate: '2025-01-22',
    estimatedTime: '6h',
    type: 'Documentation',
    dependencyIds: ['task-001'],
  },
  {
    id: 'task-003',
    name: 'Design brand color swatch exports for print',
    projectId: 'proj-001',
    status: 'Done',
    priority: 'P2',
    dueDate: '2025-01-08',
    estimatedTime: '1h',
    type: 'Design',
    dependencyIds: [],
    completedOn: '2025-01-07',
  },
  {
    id: 'task-004',
    name: 'Write ad copy for Facebook/Instagram carousel',
    projectId: 'proj-002',
    status: 'Not Started',
    priority: 'P0',
    dueDate: '2025-01-14',
    estimatedTime: '3h',
    type: 'Copy',
    dependencyIds: [],
  },
  {
    id: 'task-005',
    name: 'Design 5 ad creative variants (static)',
    projectId: 'proj-002',
    status: 'In Progress',
    priority: 'P0',
    dueDate: '2025-01-16',
    estimatedTime: '8h',
    type: 'Design',
    dependencyIds: ['task-004'],
  },
  {
    id: 'task-006',
    name: 'Set up Meta Ads campaign structure',
    projectId: 'proj-002',
    status: 'Not Started',
    priority: 'P1',
    dueDate: '2025-01-20',
    estimatedTime: '2h',
    type: 'Media Buying',
    dependencyIds: ['task-005'],
  },
  {
    id: 'task-007',
    name: 'Final color grade + export master file',
    projectId: 'proj-003',
    status: 'In Progress',
    priority: 'P0',
    dueDate: '2025-01-13',
    estimatedTime: '5h',
    type: 'Post Production',
    dependencyIds: [],
  },
  {
    id: 'task-008',
    name: 'Client review and feedback round 2',
    projectId: 'proj-003',
    status: 'Blocked',
    priority: 'P1',
    dueDate: '2025-01-17',
    estimatedTime: '1h',
    type: 'Review',
    dependencyIds: ['task-007'],
    notes: 'Blocked waiting on client scheduling.',
  },
  {
    id: 'task-009',
    name: 'Competitive audit — top 10 agency websites',
    projectId: 'proj-004',
    status: 'Done',
    priority: 'P2',
    dueDate: '2025-01-10',
    estimatedTime: '3h',
    type: 'Research',
    dependencyIds: [],
    completedOn: '2025-01-09',
  },
  {
    id: 'task-010',
    name: 'Draft website sitemap and IA',
    projectId: 'proj-004',
    status: 'In Progress',
    priority: 'P1',
    dueDate: '2025-01-24',
    estimatedTime: '4h',
    type: 'Strategy',
    dependencyIds: ['task-009'],
  },
  {
    id: 'task-011',
    name: 'Book venue and confirm catering',
    projectId: 'proj-005',
    status: 'Done',
    priority: 'P1',
    dueDate: '2025-01-05',
    estimatedTime: '2h',
    type: 'Logistics',
    dependencyIds: [],
    completedOn: '2025-01-04',
  },
  {
    id: 'task-012',
    name: 'Get print quotes from 3 vendors',
    projectId: 'proj-006',
    status: 'Not Started',
    priority: 'P3',
    dueDate: '2025-02-01',
    estimatedTime: '1h',
    type: 'Ops',
    dependencyIds: [],
  },
  {
    id: 'task-013',
    name: 'Write Q1 content calendar for Larchmont social',
    projectId: 'proj-001',
    status: 'Not Started',
    priority: 'P1',
    dueDate: '2025-01-18',
    estimatedTime: '3h',
    type: 'Strategy',
    dependencyIds: [],
  },
  {
    id: 'task-014',
    name: 'Create landing page wireframes for ScaleGenie',
    projectId: 'proj-004',
    status: 'Not Started',
    priority: 'P0',
    dueDate: '2025-01-21',
    estimatedTime: '6h',
    type: 'Design',
    dependencyIds: ['task-010'],
  },
  {
    id: 'task-015',
    name: 'Export final deliverables package for client',
    projectId: 'proj-003',
    status: 'Not Started',
    priority: 'P2',
    dueDate: '2025-01-25',
    estimatedTime: '2h',
    type: 'Delivery',
    dependencyIds: ['task-008'],
  },
]

export const mockBriefs: CreativeBrief[] = [
  {
    id: 'brief-001',
    name: 'Larchmont Brand Identity Brief',
    projectId: 'proj-001',
    type: 'Brand',
    status: 'Approved',
    objective: 'Establish Larchmont Builds as the most trusted, premium water damage restoration brand in the region. The brand should feel authoritative, clean, and human — like a contractor you actually want in your home.',
    targetAudience: 'Homeowners 35–65, middle to upper-middle income, property-conscious. Secondary: insurance adjusters and real estate agents.',
    tone: ['Trustworthy', 'Direct', 'Premium', 'Human', 'Confident'],
    colorGradeDirection: 'Warm whites, deep charcoal, single gold accent. Never cold or clinical.',
    copyDirection: 'Short, declarative sentences. Lead with outcome, not process.',
    deliverables: 'Logo suite (4 variants), color system, typography spec, brand guidelines PDF, social templates (3 formats)',
    approvalDate: '2024-11-15',
    moodBoardImages: [
      { url: '/placeholder/mood-1.jpg', caption: 'Warm contractor texture' },
      { url: '/placeholder/mood-2.jpg', caption: 'Premium minimalist service brand' },
      { url: '/placeholder/mood-3.jpg', caption: 'Before/after restoration reference' },
    ],
    shots: [],
    resourceIds: ['res-001'],
  },
  {
    id: 'brief-002',
    name: 'ScaleGenie Launch Video Ad Brief',
    projectId: 'proj-002',
    type: 'Video',
    status: 'In Production',
    objective: 'A 30-second video ad that communicates the core value prop of ScaleGenie to burned-out agency owners who are doing everything manually.',
    targetAudience: 'Agency owners 28–45, $250K–$2M ARR, frustrated with manual processes and inconsistent lead flow.',
    tone: ['Urgent', 'Punchy', 'Empowering', 'Bold'],
    lensNotes: 'Sony 24mm 1.4 for talking head. Go tight. Urban office aesthetic.',
    colorGradeDirection: 'High contrast, punchy blues and whites. Think SaaS commercial energy.',
    copyDirection: 'Open on pain, pivot to solution, close on the outcome. Use "your agency" language.',
    deliverables: '30s :06s and :15s edits. Captions included. 1:1 and 9:16 formats.',
    moodBoardImages: [
      { url: '/placeholder/mood-4.jpg', caption: 'SaaS energy reference' },
      { url: '/placeholder/mood-5.jpg', caption: 'Urban office tone' },
    ],
    shots: [
      {
        id: 'shot-001',
        shotNumber: 1,
        lens: 'Sony 24mm 1.4',
        frame: 'MCU',
        movement: 'Static',
        light: 'Practical + LED panel key',
        gradeTarget: 'High contrast, punchy',
        emotionalIntent: 'Founder staring at screen — overwhelmed but determined',
      },
      {
        id: 'shot-002',
        shotNumber: 2,
        lens: 'Sony 85mm 1.4',
        frame: 'CU on hands typing',
        movement: 'Slight push in',
        light: 'Backlit desk lamp glow',
        gradeTarget: 'Warm shadows, cool highlights',
        emotionalIntent: 'The manual grind — mundane and exhausting',
      },
      {
        id: 'shot-003',
        shotNumber: 3,
        lens: 'Sony 24mm 1.4',
        frame: 'WS office',
        movement: 'Handheld energy, slight move left',
        light: 'Natural window + bounce',
        gradeTarget: 'Clean and bright — the after',
        emotionalIntent: 'Freedom. Everything handled.',
      },
    ],
    resourceIds: ['res-003'],
  },
  {
    id: 'brief-003',
    name: 'Larchmont Hero Brand Film Brief',
    projectId: 'proj-003',
    type: 'Video',
    status: 'Locked',
    objective: 'A 90-second cinematic brand film showing the complete transformation: from a devastating water damage event to a fully restored, beautiful home — with the Larchmont team at the center of that story.',
    targetAudience: 'Homeowners who have experienced or fear property damage. Emotional, aspirational.',
    tone: ['Cinematic', 'Emotional', 'Proud', 'Expert'],
    lensNotes: 'Primary: Sony 35mm 1.4 and 85mm 1.4. Hero shots on 24mm. Close on hands and faces.',
    colorGradeDirection: 'Act 1 (damage): cold, desaturated, low contrast. Act 2 (work): mid-warm, active. Act 3 (restored): warm, golden, lifted blacks.',
    copyDirection: 'VO-led narration. Short sentences. Pause for imagery. End on brand promise.',
    deliverables: '90s hero film, 30s cut, 15s social cut. Master + social formats.',
    approvalDate: '2024-11-01',
    moodBoardImages: [
      { url: '/placeholder/mood-6.jpg', caption: 'Act 1 - cold damage reference' },
      { url: '/placeholder/mood-7.jpg', caption: 'Act 3 - warm restoration glow' },
    ],
    shots: [
      {
        id: 'shot-004',
        shotNumber: 1,
        lens: '24mm 1.4',
        frame: 'EWS exterior damaged home',
        movement: 'Slow push in',
        light: 'Natural overcast morning',
        gradeTarget: 'Desaturated, cold',
        emotionalIntent: 'The weight of the situation. Something precious at risk.',
      },
      {
        id: 'shot-005',
        shotNumber: 2,
        lens: '85mm 1.4',
        frame: 'CU homeowner face',
        movement: 'Static',
        light: 'Backlit, soft fill',
        gradeTarget: 'Cold desaturated, single warm highlight',
        emotionalIntent: 'Worry turning to hope as the Larchmont van arrives.',
      },
      {
        id: 'shot-006',
        shotNumber: 3,
        lens: '35mm 1.4',
        frame: 'MS technician working',
        movement: 'Dolly right to left',
        light: 'Work light practical, LED key',
        gradeTarget: 'Mid-warm, operational',
        emotionalIntent: 'Competence. This person knows exactly what they are doing.',
      },
    ],
    resourceIds: ['res-004'],
  },
  {
    id: 'brief-004',
    name: 'ScaleGenie Facebook Ad Campaign Brief',
    projectId: 'proj-002',
    type: 'Ad Campaign',
    status: 'In Production',
    objective: 'Drive 200 qualified demos booked in 30 days. Target agency owners who are running ads manually or relying entirely on referrals.',
    targetAudience: 'Agency owners 28–45 on Facebook/Instagram. Interest-based: marketing tools, business growth, entrepreneurship.',
    tone: ['Direct', 'Bold', 'Urgent', 'Outcome-focused'],
    copyDirection: 'Hook in 3 words. Problem in 1 sentence. Solution in 1 sentence. CTA with friction reduction.',
    deliverables: '5 static ad creatives, 3 copy variants per creative, 30s video ad.',
    moodBoardImages: [
      { url: '/placeholder/mood-8.jpg', caption: 'Direct response energy' },
    ],
    shots: [],
    resourceIds: ['res-003'],
  },
]

export const mockCampaigns: Campaign[] = [
  {
    id: 'camp-001',
    name: 'ScaleGenie Q1 2025 Launch',
    goal: 'Lead Gen',
    status: 'Active',
    startDate: '2025-01-01',
    endDate: '2025-03-31',
    budget: 15000,
    channels: ['Facebook Ads', 'Instagram Ads', 'Google Ads', 'Email'],
    projectIds: ['proj-002'],
    kpis: '200 demos booked, CPL < $75, ROAS > 3x',
    targetAudience: 'Agency owners, $250K–$2M ARR',
    results: 'Live — 47 demos booked in first 2 weeks.',
  },
  {
    id: 'camp-002',
    name: 'Larchmont Brand Awareness Push',
    goal: 'Awareness',
    status: 'Active',
    startDate: '2024-12-15',
    endDate: '2025-02-28',
    budget: 4500,
    channels: ['Facebook Ads', 'YouTube', 'Direct Mail'],
    projectIds: ['proj-001', 'proj-003'],
    kpis: 'Reach 50K+ in target zip codes, Brand recall +15%',
    targetAudience: 'Homeowners 35–65, 20-mile radius',
  },
]

export const mockAssets: Asset[] = [
  {
    id: 'asset-001',
    name: 'Larchmont Logo — Primary Lockup',
    type: 'Logo',
    projectId: 'proj-001',
    status: 'Final',
    fileUrl: '/assets/larchmont-logo-primary.svg',
    format: 'SVG',
    version: 3,
    createdOn: '2024-12-01',
    notes: 'Final approved version. Use on all white/light backgrounds.',
  },
  {
    id: 'asset-002',
    name: 'Larchmont Logo — Dark Variant',
    type: 'Logo',
    projectId: 'proj-001',
    status: 'Final',
    fileUrl: '/assets/larchmont-logo-dark.svg',
    format: 'SVG',
    version: 2,
    createdOn: '2024-12-01',
  },
  {
    id: 'asset-003',
    name: 'ScaleGenie Ad Set A — Static Creative v1',
    type: 'Ad Creative',
    projectId: 'proj-002',
    campaignId: 'camp-001',
    status: 'In Review',
    thumbnailUrl: '/placeholder/ad-thumb-1.jpg',
    format: 'PNG 1080x1080',
    version: 1,
    createdOn: '2025-01-08',
    notes: 'Needs copy revision per feedback from round 1.',
  },
  {
    id: 'asset-004',
    name: 'ScaleGenie Ad Set B — Static Creative v1',
    type: 'Ad Creative',
    projectId: 'proj-002',
    campaignId: 'camp-001',
    status: 'Draft',
    format: 'PNG 1080x1080',
    version: 1,
    createdOn: '2025-01-09',
  },
  {
    id: 'asset-005',
    name: 'Hero Brand Film — Master Cut',
    type: 'Video',
    projectId: 'proj-003',
    status: 'In Review',
    fileUrl: '/assets/larchmont-hero-master.mp4',
    format: 'MP4 4K',
    version: 2,
    createdOn: '2025-01-05',
    notes: 'Round 2 color grade. Client feedback pending.',
  },
  {
    id: 'asset-006',
    name: 'Hero Brand Film — 30s Cut',
    type: 'Video',
    projectId: 'proj-003',
    campaignId: 'camp-002',
    status: 'Draft',
    format: 'MP4 1080p',
    version: 1,
    createdOn: '2025-01-07',
  },
  {
    id: 'asset-007',
    name: 'Customer Event — Invitation Design',
    type: 'Print',
    projectId: 'proj-005',
    status: 'Final',
    format: 'PDF',
    version: 1,
    createdOn: '2024-12-15',
  },
  {
    id: 'asset-008',
    name: 'Business Card Design — Front',
    type: 'Print',
    projectId: 'proj-006',
    status: 'Draft',
    format: 'AI',
    version: 1,
    createdOn: '2024-11-20',
  },
]

export const mockResources: ResourceItem[] = [
  {
    id: 'res-001',
    name: 'The Brand Gap — Marty Neumeier',
    category: 'Brand Strategy',
    type: 'Book',
    sourceUrl: 'https://example.com/brand-gap',
    summary: 'Foundational framework for understanding brand as a gut feeling, not a logo. The 5 disciplines: differentiate, collaborate, innovate, validate, cultivate.',
    tags: ['branding', 'strategy', 'positioning', 'foundational'],
    linkedProjectIds: ['proj-001'],
    linkedBriefIds: ['brief-001'],
    addedOn: '2024-10-01',
  },
  {
    id: 'res-002',
    name: 'Zag — Marty Neumeier',
    category: 'Brand Strategy',
    type: 'Book',
    sourceUrl: 'https://example.com/zag',
    summary: 'When everyone zigs, zag. Radical differentiation as competitive strategy. Includes the "onliness statement" framework.',
    tags: ['differentiation', 'positioning', 'competitive strategy'],
    linkedProjectIds: ['proj-001'],
    linkedBriefIds: [],
    addedOn: '2024-10-05',
  },
  {
    id: 'res-003',
    name: 'Alex Hormozi — $100M Offers Framework',
    category: 'Copy',
    type: 'Course Notes',
    summary: 'Value equation: Dream outcome × perceived likelihood of achievement / time delay × effort & sacrifice. Grand slam offer anatomy.',
    tags: ['offers', 'copywriting', 'direct response', 'SaaS'],
    linkedProjectIds: ['proj-002'],
    linkedBriefIds: ['brief-002', 'brief-004'],
    addedOn: '2024-09-15',
  },
  {
    id: 'res-004',
    name: 'Roger Deakins — Interview on Natural Light',
    category: 'Cinematography',
    type: 'Interview',
    sourceUrl: 'https://example.com/deakins-light',
    summary: 'Deakins on motivated lighting — every source should exist in the world of the story. Natural light as reference, never as sole source.',
    tags: ['cinematography', 'lighting', 'natural light', 'reference'],
    linkedProjectIds: ['proj-003'],
    linkedBriefIds: ['brief-003'],
    addedOn: '2024-08-20',
  },
  {
    id: 'res-005',
    name: 'Color Grading Academy — Emotional Color Language',
    category: 'Color',
    type: 'Course',
    summary: 'Warm-cool split for narrative contrast. Cold for conflict, warm for resolution. Teal-orange for cinematic energy.',
    tags: ['color grading', 'emotion', 'storytelling', 'DaVinci Resolve'],
    linkedProjectIds: ['proj-003'],
    linkedBriefIds: ['brief-003'],
    addedOn: '2024-09-01',
  },
  {
    id: 'res-006',
    name: 'Conversion Rate Experts — Web Copy Teardowns',
    category: 'Copy',
    type: 'Resource Collection',
    sourceUrl: 'https://example.com/cre',
    summary: 'Above-fold hierarchy: headline (outcome), subhead (method), social proof, CTA. No fluff. Every word earns its place.',
    tags: ['web copy', 'conversion', 'UX writing', 'landing pages'],
    linkedProjectIds: ['proj-004'],
    linkedBriefIds: [],
    addedOn: '2024-11-10',
  },
  {
    id: 'res-007',
    name: 'Influence — Robert Cialdini',
    category: 'Psychology',
    type: 'Book',
    summary: 'The 7 principles: reciprocity, commitment/consistency, social proof, authority, liking, scarcity, unity. Applied to every marketing touchpoint.',
    tags: ['psychology', 'persuasion', 'marketing', 'behavioral'],
    linkedProjectIds: [],
    linkedBriefIds: [],
    addedOn: '2024-07-01',
  },
  {
    id: 'res-008',
    name: 'Story — Robert McKee',
    category: 'Copy',
    type: 'Book',
    summary: 'Story as the fundamental unit of meaning. Gap-gap-gap structure. Protagonist desire → obstacle → resolution. Direct application to brand film structure.',
    tags: ['storytelling', 'narrative', 'screenplay', 'brand video'],
    linkedProjectIds: ['proj-003'],
    linkedBriefIds: ['brief-003'],
    addedOn: '2024-08-10',
  },
  {
    id: 'res-009',
    name: 'Ogilvy on Advertising',
    category: 'Copy',
    type: 'Book',
    summary: 'The consumer is not a moron, she is your wife. Headline must carry the entire message. Research as foundation for all creative decisions.',
    tags: ['advertising', 'copywriting', 'direct response', 'classic'],
    linkedProjectIds: ['proj-002'],
    linkedBriefIds: ['brief-004'],
    addedOn: '2024-06-15',
  },
  {
    id: 'res-010',
    name: 'Legal — FTC Disclosure Guidelines for Social Ads',
    category: 'Legal',
    type: 'Document',
    sourceUrl: 'https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers',
    summary: 'Required disclosures for paid ads and sponsored content. #ad, #sponsored placement rules. Applies to all ScaleGenie and Larchmont social.',
    tags: ['legal', 'compliance', 'social media', 'FTC'],
    linkedProjectIds: ['proj-002'],
    linkedBriefIds: [],
    addedOn: '2024-10-20',
  },
]

export const mockEvents: EventRecord[] = [
  {
    id: 'event-001',
    name: 'Larchmont Hero Film — Final Production Day',
    type: 'Production Shoot',
    projectId: 'proj-003',
    dateTime: '2025-01-18T08:00:00',
    location: '4821 Maple Ave, Lakewood — Restoration Site',
    status: 'Confirmed',
    callTime: '7:30 AM',
    crew: 'DP: Marcus Webb | AC: Jess Torres | Gaffer: Dan Miller | PA: 2x',
    deliverablesExpected: 'Final exterior establishing shots, hero restoration sequence, client testimonial interview',
    contingencyNotes: 'Backup location secured at HQ if weather does not cooperate. Generator on standby.',
  },
  {
    id: 'event-002',
    name: 'Customer Appreciation BBQ & Brand Activation',
    type: 'Brand Event',
    projectId: 'proj-005',
    dateTime: '2025-01-25T12:00:00',
    location: 'Larchmont HQ — Parking Lot + Tent',
    status: 'Confirmed',
    crew: 'Catering: 4 staff | Brand team: 2 | Photography: 1',
    deliverablesExpected: 'Photography of 200+ attendees, testimonial video clips, brand activation documentation',
  },
  {
    id: 'event-003',
    name: 'ScaleGenie Strategy Call — Q1 Campaign Review',
    type: 'Client Meeting',
    projectId: 'proj-002',
    dateTime: '2025-01-20T10:00:00',
    location: 'Zoom',
    status: 'Planned',
    deliverablesExpected: 'Campaign performance deck, revised targeting recommendations',
  },
]

export const mockContent: ContentItem[] = [
  {
    id: 'content-001',
    title: 'What Actually Happens After Water Damage (The Truth Nobody Tells You)',
    format: 'Long Form',
    platforms: ['YouTube', 'Website'],
    status: 'In Edit',
    projectId: 'proj-003',
    briefId: 'brief-003',
    shootDate: '2025-01-10',
    hook: 'Most homeowners do this one thing that makes the damage worse...',
    cta: 'Get a free assessment — link in description',
  },
  {
    id: 'content-002',
    title: 'How We Restored This Home in 72 Hours (Time Lapse)',
    format: 'Short Form',
    platforms: ['Instagram Reels', 'TikTok', 'YouTube Shorts'],
    status: 'Shot',
    projectId: 'proj-003',
    shootDate: '2025-01-10',
    hook: '72 hours. Complete disaster to move-in ready.',
    cta: 'Save this if you own a home',
  },
  {
    id: 'content-003',
    title: 'Stop Running Your Agency Like It\'s 2019',
    format: 'Short Form',
    platforms: ['Instagram Reels', 'LinkedIn'],
    status: 'Scripted',
    projectId: 'proj-002',
    campaignId: 'camp-001',
    hook: 'You are manually doing 4 things that should be automated by 9am tomorrow.',
    cta: 'Comment "scale" to get the checklist',
  },
  {
    id: 'content-004',
    title: 'The Agency Owner\'s Morning Routine That Changes Everything',
    format: 'Podcast',
    platforms: ['Spotify', 'Apple Podcasts', 'YouTube'],
    status: 'Idea',
    projectId: 'proj-002',
    hook: 'What separates $500K agencies from $2M agencies? Their mornings.',
  },
  {
    id: 'content-005',
    title: 'Larchmont Brand Story — From Side Hustle to Regional Leader',
    format: 'Documentary',
    platforms: ['YouTube', 'Facebook'],
    status: 'Scripted',
    projectId: 'proj-001',
    briefId: 'brief-001',
    hook: 'He started with a borrowed truck and a YouTube tutorial.',
    cta: 'Follow along as we tell the full story',
  },
  {
    id: 'content-006',
    title: 'ScaleGenie vs. Doing It All Yourself — Honest Breakdown',
    format: 'Long Form',
    platforms: ['YouTube'],
    status: 'Idea',
    projectId: 'proj-002',
    campaignId: 'camp-001',
    hook: 'I\'m going to break down exactly what you\'re spending 4 hours a day doing that a $99/mo tool should handle.',
  },
  {
    id: 'content-007',
    title: 'Agency Owner Cold Email That Books 20 Calls/Month',
    format: 'Email',
    platforms: ['Email List'],
    status: 'Scheduled',
    projectId: 'proj-002',
    publishDate: '2025-01-20',
    hook: 'You\'ve been writing cold emails wrong. Here\'s the 4-sentence template.',
    cta: 'Try ScaleGenie free for 14 days',
  },
  {
    id: 'content-008',
    title: 'We Filmed A Real Water Damage Job — Here\'s What We Found',
    format: 'Short Form',
    platforms: ['TikTok', 'Instagram Reels'],
    status: 'Published',
    projectId: 'proj-003',
    publishDate: '2025-01-05',
    hook: 'The homeowner had no idea how bad it really was.',
    performanceNotes: '284K views TikTok, 47K Instagram. Best performing content to date.',
  },
]

export const mockInbox: InboxItem[] = [
  {
    id: 'inbox-001',
    text: 'Need to create a series of educational reels around mold prevention — seasonal content play, especially after winter storms. Could tie into Larchmont insurance partnerships.',
    capturedOn: '2025-01-12T09:15:00',
    type: 'Content Idea',
    status: 'New',
  },
  {
    id: 'inbox-002',
    text: 'Jason from Crosspoint Roofing wants to explore a co-marketing campaign. Thinks our audiences overlap significantly. Set up a call to discuss.',
    capturedOn: '2025-01-12T14:32:00',
    type: 'Lead/Opportunity',
    status: 'New',
  },
  {
    id: 'inbox-003',
    text: 'Look into hiring a dedicated video editor — we\'re at the point where the turnaround time is the bottleneck. Budget for $3–4K/month contractor or explore offshore option.',
    capturedOn: '2025-01-11T11:00:00',
    type: 'Task',
    status: 'New',
  },
  {
    id: 'inbox-004',
    text: 'https://readymag.com/u2778563/brand-case-study/ — amazing brand case study. Reference for how to present the Larchmont story. Especially the before/after narrative structure.',
    capturedOn: '2025-01-10T20:44:00',
    type: 'Resource',
    status: 'New',
  },
  {
    id: 'inbox-005',
    text: 'Consider adding a referral program to Larchmont — plumbers, HVAC techs, and roofers all encounter water damage scenarios. Pay $500 per confirmed job lead.',
    capturedOn: '2025-01-09T08:00:00',
    type: 'Strategy',
    status: 'New',
  },
]
